name: Build nightly

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Store generated APK file
      uses: actions/upload-artifact@v4
      with:
        name: termux-boot
        path: ./app/build/outputs/apk/debug/app-debug.apk
